## my first graph


In [1]:
import tensorflow as tf
A = tf.random_uniform([5,5])
B = tf.random_uniform([5,5])
C = tf.matmul(A,B)
print(C);
session = tf.Session()
session.run(C)

print("A")
print(session.run(A))

print("B")
print(session.run(B))

print("C")
print(session.run(C))

writer = tf.train.SummaryWriter("/tmp/start1", session.graph)


Tensor("MatMul:0", shape=(5, 5), dtype=float32)
A
[[ 0.83507776  0.21948612  0.37569809  0.40677381  0.76023221]
 [ 0.65436685  0.29018974  0.459342    0.02286196  0.83304226]
 [ 0.72508967  0.63782382  0.66243649  0.99468386  0.49296641]
 [ 0.13798761  0.84818196  0.16287172  0.944368    0.30115712]
 [ 0.31632483  0.98446143  0.27488148  0.91331947  0.06971109]]
B
[[ 0.52408695  0.29631042  0.75476706  0.98430967  0.93703926]
 [ 0.10937321  0.92656887  0.75044656  0.43800724  0.54509318]
 [ 0.61250556  0.17846298  0.20133805  0.8509022   0.23952317]
 [ 0.06808686  0.85807931  0.51301527  0.08932102  0.69580662]
 [ 0.85242712  0.40909648  0.5158937   0.22837746  0.59773886]]
C
[[ 0.81757271  0.58452368  0.8921777   0.38989824  0.73323846]
 [ 1.32021773  0.94930142  1.10783827  0.81682581  1.03693068]
 [ 1.67880559  1.00997734  1.62000394  1.06324077  1.48489201]
 [ 1.47553682  1.00358653  1.51585937  0.82365829  1.30277228]
 [ 1.68431914  1.25301659  1.43858874  1.12672985  1.39875901]

In [4]:
tf.reset_default_graph()
session.close()

In [ ]:

import numpy as np

tf.reset_default_graph()
XData = np.random.rand(5,5)
YData = np.random.rand(5,5)

#### similar to other code but generating data and passing data to tensor

In [17]:
x = tf.placeholder(tf.float32, [5,5])
y = tf.placeholder(tf.float32, [5,5])
z = tf.matmul(x,y) #calculates matrix multiplication

with tf.Session() as session:
    session.run(tf.initialize_all_variables())
    print(session.run(z, feed_dict={x:XData, y:YData}))

[[ 0.50757235  0.80103362  0.20986789  0.83151579  0.77686781]
 [ 1.73937559  2.2497642   0.74580956  1.950104    2.20099235]
 [ 2.11346078  2.69542027  0.81798941  2.66974401  2.8874464 ]
 [ 0.89855564  1.38707566  0.37758365  1.49070978  1.54351962]
 [ 1.81329727  2.48721266  0.77378774  2.33046365  2.18435669]]


## Machine Learning 101

What is Machine learning? 
Target Function = tells you the outcome
Example: The image my eye receives is data and teh brain processes the image and tells you what it is. The procesing of the brain is a target function.
Machine learning tries to solve the learning algorithm and model to get the target function.

In a program, yo tell how an opperation will work. We code it.
Machine learning, we don't know the target function.

The learning algorithm assumes that the floor is concrete and the top concrete is ceiling. The rational of creating a threshold is learning algorithm. The threshold becomes the model.

Looks at data!!!!


Train Data. 
Problem: overfitting.  Buliding a model that fits that data perfectly. if you givit it new data, its a problem.

Training Data by creating three types of sets:
Training Set
Testing Set
validation set

Machine Learning solves
Classification problems = what it is
Regression Problem = Example: what is the demand for a given price. Price of a TV on black friday.


http://www.r2d3.us/

In [ ]:
Machine Learning Camps

Recomender Systems - Netflix

Neural Networks aka Deep Learning
- face recognition
- computer vision
- speech recognition

reverse induction
genetic evolution
Linear regression
Logistic Regression